# -*- coding: utf-8 -*-
"""TASKB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oqw8xXi6zVXxzU3Ynbx3TiPBZtPawq-n
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()
import matplotlib.pyplot as plt


df = pd.read_csv("motor_insurance_recovery_cleaned final.csv")

df.head()


# Injury column is already cleaned, so split into lists
df['injury_type_classifications'] = df['injury_type_classifications'].astype(str).str.split(", ")

# Explode so each injury appears on its own row
injury_exploded = df.explode('injury_type_classifications')

# Count most common injury types ---
injury_counts = (
    injury_exploded['injury_type_classifications']
    .value_counts()
    .reset_index()
)

injury_counts.columns = ["injury_type", "count"]

print("\n=== Most Common Injury Types ===")
print(injury_counts)


#Bar chart (matplotlib, single plot, no set colors)

plt.figure(figsize=(10, 6))
plt.bar(injury_counts['injury_type'], injury_counts['count'])
plt.xticks(rotation=90)
plt.title("Most Common Injury Types")
plt.xlabel("Injury Type")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

#Doing combinations of 2
# Convert comma-separated string → list (simple & required for combinations)
df['inj_list'] = df['injury_type_classifications'].astype(str).str.split(", ")

# Sort list so order (A,B) = (B,A)
df['inj_list'] = df['inj_list'].apply(sorted)

# Count number of injuries in the list
df['n_injuries'] = df['inj_list'].str.len()
# Keep only combinations of size 2
combo_df = df[df['n_injuries'] == 2].copy()

# Turn list back into a string for counting
combo_df['injury_combination'] = combo_df['inj_list'].apply(", ".join)

# Count most common 2 injury combinations
combo_counts = (
    combo_df['injury_combination']
    .value_counts()
    .reset_index()
)
combo_counts.columns = ["injury_combination", "count"]

print("\n=== Most Common Injury Combinations (2–3 injuries) ===")
print(combo_counts.head(20))

# Top 10 2-injury combinations
top_10 = combo_counts.head(10)

plt.figure(figsize=(10, 6))

# Horizontal bar chart
plt.barh(top_10['injury_combination'], top_10['count'])
plt.xlabel("Count")
plt.ylabel("Injury Combination")
plt.title("Top 10 Most Common 2-Injury Combinations")
plt.gca().invert_yaxis()  # biggest on top
plt.tight_layout()
plt.show()

# Convert comma-separated string into list
df['inj_list'] = df['injury_type_classifications'].astype(str).str.split(", ")

# Sort so order doesn't matter
df['inj_list'] = df['inj_list'].apply(sorted)

# Count number of injuries
df['n_injuries'] = df['inj_list'].str.len()

# Keep only combinations with EXACTLY 3 injuries
combo_3 = df[df['n_injuries'] == 3].copy()

# Convert back to string for counting
combo_3['injury_combination'] = combo_3['inj_list'].apply(", ".join)

# Count most common 3-injury combos
combo_3_counts = (
    combo_3['injury_combination']
    .value_counts()
    .reset_index()
)

combo_3_counts.columns = ["injury_combination", "count"]

print("\n=== Most Common 3-Injury Combinations ===")
print(combo_3_counts.head(20))

top_5_3 = combo_3_counts.head(5)

plt.figure(figsize=(14, 6))  # wide so text is readable

plt.barh(top_5_3['injury_combination'], top_5_3['count'])
plt.xlabel("Count")
plt.ylabel("3-Injury Combination")
plt.title("Top 5 Most Common 3-Injury Combinations")

plt.gca().invert_yaxis()  # largest at top
plt.tight_layout()        # ensures labels don't get cut off
plt.show()

#Injury types & claim amount association
# Converting comma-separated injuries into a list
df['inj_list'] = df['injury_type_classifications'].astype(str).str.split(", ")

# Explode so each injury becomes its own row
injury_exploded = df.explode('inj_list').copy()
injury_exploded.rename(columns={'inj_list': 'injury_type'}, inplace=True)
# average claim amount per injury type
avg_claim_per_injury = (
    injury_exploded.groupby('injury_type')['total_claim_amount']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

print("\n -Average Claim Amount by Injury Type  - ")
print(avg_claim_per_injury)

top_injuries = avg_claim_per_injury.head(10)   # or all injuries

plt.figure(figsize=(12, 6))
plt.barh(top_injuries['injury_type'], top_injuries['total_claim_amount'])
plt.xlabel("Average Claim Amount (£)")
plt.ylabel("Injury Type")
plt.title("Average Claim Amount by Injury Type")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

#Average recovery time and claim amount association

# Average recovery duration per injury type
avg_recovery_per_injury = (
    injury_exploded.groupby('injury_type')['injury_duration_days']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

print("\n=== Average Recovery Time (Days) by Injury Type ===")
print(avg_recovery_per_injury)

top_duration = avg_recovery_per_injury.head(10)

plt.figure(figsize=(12, 6))
plt.barh(top_duration['injury_type'], top_duration['injury_duration_days'])
plt.xlabel("Average Injury Duration (Days)")
plt.ylabel("Injury Type")
plt.title("Average Recovery Duration by Injury Type")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

#Merging both tables already created :
# Merge average claim amount and average recovery time on injury_type
injury_severity = avg_claim_per_injury.merge(
    avg_recovery_per_injury,
    on='injury_type',
    how='inner'
)

print("\n=== Combined table: Avg Claim Amount & Avg Recovery Time by Injury Type ===")
print(injury_severity)


plt.figure(figsize=(8, 6))

plt.scatter(
    injury_severity['injury_duration_days'],
    injury_severity['total_claim_amount']
)

plt.xlabel("Average Recovery Time (days)")
plt.ylabel("Average Claim Amount (£)")
plt.title("Injury Types: Average Claim Amount vs Recovery Time")

plt.tight_layout()
plt.show()


# Sorting injuries by claim amount or recovery time for readability
injury_severity_sorted = injury_severity.sort_values("total_claim_amount", ascending=False)

# Create figure
fig, ax1 = plt.subplots(figsize=(14, 6))

# (Average Claim Amount) BAR chart
bars = ax1.bar(
    injury_severity_sorted['injury_type'],
    injury_severity_sorted['total_claim_amount'],
    alpha=0.7
)

ax1.set_xlabel("Injury Type")
ax1.set_ylabel("Average Claim Amount (£)", color="black")
ax1.tick_params(axis='y', labelcolor="black")
plt.xticks(rotation=90)

#  SECOND AXIS (Line: Average Recovery Time)
ax2 = ax1.twinx()
ax2.plot(
    injury_severity_sorted['injury_type'],
    injury_severity_sorted['injury_duration_days'],
    color="black",
    marker="o",
    linewidth=2
)

ax2.set_ylabel("Average Recovery Time (days)", color="black")
ax2.tick_params(axis='y', labelcolor="black")

#  Title
plt.title("Average Claim Amount and Recovery Duration by Injury Type")

plt.tight_layout()
plt.show()

#Recommendation rate of Rehabilitation
rec_rate = df['rehabilitation_recommended'].mean()
comp_rate = df['rehabilitation_completed'].mean()

print("Rehabilitation recommended:", round(rec_rate*100,2), "%")
print("Rehabilitation completed:", round(comp_rate*100,2), "%")

#Completion Rate among the recommonded Rehabilitation
conditional_completion = (
    df[df["rehabilitation_recommended"] == 1]["rehabilitation_completed"].mean()
)

print("Completion rate among recommended:", round(conditional_completion*100,2), "%")

#Trying to understand rehabilitation effectivness by analyzing rehabilitation rates vs outcome columns :
outcome_cols = [
    "injury_duration_days",
    "work_absence_duration_days",
    "general_damages",
    "total_claim_amount"
]

df.groupby("rehabilitation_completed")[outcome_cols].mean()

"""Does rehabilitation change recovery outcomes or claim costs?
Rehab completion is correlated with more severe injuries.

More severe injuries shows higher general damages & higher total claim amounts.

Rehab does not reduce injury duration in this dataset.
"""

from collections import Counter

def count_injuries(subset):
    all_injuries = []
    for s in subset["injury_type_classifications"]:
        all_injuries.extend(list(s))
    return Counter(all_injuries)

inj_rec = count_injuries(df[df["rehabilitation_recommended"] == 1])
inj_not_rec = count_injuries(df[df["rehabilitation_recommended"] == 0])

print("Top Injuries — Rehab Recommended:")
print(inj_rec.most_common(10))

import matplotlib.pyplot as plt

df["rehab_group"] = df["rehabilitation_recommended"].map({0:"Not Recommended", 1:"Recommended"})

df["rehab_group"].value_counts().plot(kind="bar")
plt.title("Rehabilitation Recommendation Distribution")
plt.show()

df.boxplot(column="total_claim_amount", by="rehabilitation_completed")
plt.title("Total Claim Amount by Rehab Completion")
plt.suptitle("")
plt.show()
#We can also get the mean claim amount for each *

"""First graph shows How often is rehabilitation recommended in the dataset.
and the second graph shows :How does completing rehabilitation relate to total claim cost?
"""

#Testing Sample to be used in 2.3

task_b_test_data = {
 "client_id": [1.0, 6.0, 8.0],
 "claim_value_category": [1.0, 2.0, 2.0],
 "injury_duration_days": [33.0, 44.0, 42.0],
 "hospital_visit_required": [1.0, 1.0, 1.0],
 "medical_care_sought": [1.0, 1.0, 1.0],
 "hospital_admission_required": [0.0, 0.0, 1.0],
 "currently_unemployed_due_to_injury": [0.0, 1.0, 0.0],
 "work_absence_duration_days": [2.0, 12.0, 0.0],
 "work_absence_required": [0.0, 1.0, 0.0],
 "rehabilitation_recommended": [0.0, 1.0, 1.0],
 "rehabilitation_completed": [0.0, 1.0, 1.0],
 "minor_claimant_at_initial_assessment": [0.0, 0.0, 0.0],
 "defendant_title_code": [0.0, 1.0, 0.0],
 "liability_admission_status": ["A", "A", "A"],
 "liability_type": ["motor", "motor", "motor"],
 "claimant_age_at_incident": [55.0, 31.0, 47.0],
 "liability_denial_reasons": ["", "", ""],
 "claim_rejection_code": ["", "", ""],
 "claims_management_exit_notes": ["", "", ""],
 "claims_resolution_exit_notes": ["", "", ""],
 "claims_resolution_closure_code": ["", "", ""],
 "rental_vehicle_expense": [0.0, 0.0, 0.0],
 "home_care_services_cost": [0.0, 0.0, 0.0],
 "employment_disadvantage_compensation": [0.0, 0.0, 0.0],
 "career_satisfaction_loss_compensation": [0.0, 0.0, 0.0],
 "asset_utility_loss_compensation": [0.0, 0.0, 0.0],
 "medical_treatment_costs": [125.32, 250.73, 500.12],
 "general_damages": [6056.74, 14563.83, 24008.63],
 "insurance_deductible_amount": [50.0, 100.0, 0.0],
 "car_damage_severity": ["none", "minor", "severe"],
 "total_claim_amount": [6232.06, 14914.56, 24508.75],
 "injury_type_classifications": [
    "{'Internal Injury', 'Psychological Issues'}",
    "{'Facial Injury', 'Psychological Issues', 'Soft Tissue Injury'}",
    "{'Head Injury', 'Internal Injury'}"
 ],
 "rehabilitation_program_types": [
    "{'Unknown'}",
    "{'exercises', 'pain relief'}",
    "{'miscellaneous', 'scans and imaging', 'surgery'}"
 ],
 "claimant_current_age_years": [55.0, 31.0, 47.0],
 "medical_attention_delay_days": [0.0, 0.0, 0.0],
 "emergency_services_attended": ["none", "ambulance", "ambulance_and_police"]
}

df_samples_task_b = pd.DataFrame(task_b_test_data)

#Task 2.3
#Creating a map to label the severity of each injury after looking at AIS & other proxy indicators from the data set

#assigning a severity number to each injury type. - logical
import ast
injury_severity_map = {
    "Soft Tissue Injury": 1,
    "Whiplash": 1,
    "Psychological Issues": 2,
    "Facial Injury": 2,
    "Head Injury": 3,
    "Internal Injury": 4
}
#get_ais_scores will return a list of injury AIS scores for each list of injuries
def get_ais_scores(injuries):
    return [injury_severity_map.get(i, 1) for i in injuries]  # default = 1
df["ais_scores"] = df["injury_type_classifications"].apply(get_ais_scores)
#adds a new column showing each claimant’s list of AIS values.


#ISS-style injury severity score
#taking the 3 most severe injuries , squaring them , and adding them together (based on ISS)
def compute_iss(ais_list):
    if len(ais_list) == 0:
        return 0
    top3 = sorted(ais_list, reverse=True)[:3]
    return sum([x**2 for x in top3])

df["iss_score"] = df["ais_scores"].apply(compute_iss)
#Proxy indicator 1  :using car damage and converting it into severity number scale
car_damage_map = {"none":0, "minor":1, "moderate":2, "severe":3}
df["car_damage_score"] = df["car_damage_severity"].map(car_damage_map)

df["final_severity_score"] = (
    df["iss_score"] +
    (df["injury_duration_days"] / 10) +
    df["car_damage_score"] +
    df["rehabilitation_recommended"] * 1 +
    df["rehabilitation_completed"] * 1.5 +
    (df["general_damages"] / 10000)
)

df_samples_task_b["injury_type_classifications"] = df_samples_task_b["injury_type_classifications"].apply( lambda x: ast.literal_eval(x) if pd.notnull(x) else [] )
df_samples_task_b["ais_scores"] = df_samples_task_b["injury_type_classifications"].apply(get_ais_scores)
df_samples_task_b["iss_score"] = df_samples_task_b["ais_scores"].apply(compute_iss)
df_samples_task_b["final_severity_score"] = ( df_samples_task_b["iss_score"] + (df_samples_task_b["injury_duration_days"] / 10)
+ df_samples_task_b["car_damage_severity"].map(car_damage_map)
+ df_samples_task_b["rehabilitation_recommended"] * 1 + df_samples_task_b["rehabilitation_completed"] * 1.5 + (df_samples_task_b["general_damages"] / 10000) )
df_samples_task_b[["client_id", "final_severity_score"]]